### ISSUE TITLE
Unit Tests + Coverage

### ISSUE THREAD

**Issue by bnels** [DeepLearnPhysics/lartpc_mlreco3d#14]
We should implement some basic unit tests that ensure that basic examples run, and that important functions behave in an appropriate way.

Options are:
* [unittest](https://docs.python.org/3/library/unittest.html) - pretty easy to get started with
* [pytest](https://docs.pytest.org/en/latest/) - Maybe preferable, but some more up-front investment
* ???

Once this is done, we should set up continuous integration so that things are demonstrably not broken with each commit.  We can integrate with github so that tests have to pass before a pull request can be merged
* [Travis-CI](https://github.com/marketplace/travis-ci)

After CI is set up, can set up code coverage. Options are:
* [Codecov](https://github.com/marketplace/codecov)
* [Coveralls](https://github.com/marketplace/coveralls)

We can also check coverage manually:
* [coverage](https://coverage.readthedocs.io/en/v4.5.x/)
* [dosctr-coverage](https://pypi.org/project/docstr-coverage/)

**Comment by bnels** [comment]
Travis-CI will probably require #12 to be taken care of first (no gpu).

We may also want to consider making a publicly available file with a small number of events that can be obtained via `wget` for use in testing.

**Comment by Temigo** [comment]
I started writing unit tests using pytest. Let me know if objections / prefer unittest !
