### ISSUE TITLE
MINOR: get_ppn_info() return has duplicate entries `energy_deposit` L71 and L74

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#33]
[This](https://github.com/DeepLearnPhysics/lartpc_mlreco3d/blob/develop/mlreco/utils/ppn.py#L71) and [this](https://github.com/DeepLearnPhysics/lartpc_mlreco3d/blob/develop/mlreco/utils/ppn.py#L74)

**Comment by drinkingkazu** [comment]
Well, never get attention so I changed it :) Maybe @Temigo and/or @francois-drielsma ? 

Though a rude way, https://github.com/DeepLearnPhysics/lartpc_mlreco3d/commit/adf86b8dbcb1046603577be927b4dfc6b4cfcf65 addresses this issue. There's no logical error found by `pytest`. If breaks, just remember it might be due to this fix!

**Comment by Temigo** [comment]
I think this can be closed now.
