### ISSUE TITLE
`analysis_keys` and the reduction of network output in `trainval.py::forward` seems not ideal

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#40]
`trainval.py::forward` should be one of most useful function for a user to "run the net, get the output" *unaltered* (i.e. don't call reduction like `sum` or `mean`). That should be the default. However, currently, it is optional only if one specifies `analysis_keys` in the config for ALL network output tensor keys. 

The only reason I can see why this is in `trainval.py::forward` is so that it can be reported in `main.py::log` function. Should be the other way around: the `main.py::log` function, as a consumer, should be computing a mean/count.

For both "output" and "analysis" code have capability to parse the full tensor already. So it seems we should remove those if statements in `trainval.py::forward`.

Further, though maybe unrelated... "output" and "analysis" are two different functionalities and should not be sharing a parameter `analysis_keys`. In fact, why are those separate? Storing net output as is sounds like the dumbest type of "analysis" and can be part of it.

**Comment by drinkingkazu** [comment]
assigned those who probably get hit by this change. plz comment if you oppose.

**Comment by francois-drielsma** [comment]
My two cents: I am not sure if this is clear or not but `trainval.py::_forward` as it is right now does not return the raw output of the network forward function (i.e. tensors), it returns the output of the loss function's forward function, which is typically a dictionary of scalars (accuracy, loss, etc.). I believe that currently `mean()` and `sum()` in `trainval.py::forward` do absolutely nothing, unless the loss function has an entry which is an array, which I have not seen yet, but maybe would be a good idea. Bottom line is that removing them will probably have no effect, at least as far as the models I have worked with are concerned.

**Comment by drinkingkazu** [comment]
Great: my understanding is you're ok to remove these lines. I don't think we should have multi-standards (i.e. options to support different forms) and screw ourselves up.

**Comment by francois-drielsma** [comment]
Absolutely.

**Comment by drinkingkazu** [comment]
... and I have code implemented. PR soon... sigh people woke up and emails coming in...

**Comment by drinkingkazu** [comment]
@Temigo would you give an input? I don't see why "outputs" and "analysis" should be different. Currently both of them call a custom function that takes data and/or network outputs, do something/anything, and store in csv file. As written above, it seems more natural to implement those scripts under `output_formatters` to `analysis`, and maybe rename them as `post_processing`?

Please share your thoughts!

**Comment by drinkingkazu** [comment]
https://github.com/DeepLearnPhysics/lartpc_mlreco3d/commit/768e57128cfe7dd58b939b97f4f192319cb990e9
