### ISSUE TITLE
Changing the nomenclature 

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#5]
* Function names
    `parse_particle` => `parse_particle_points`
* Configuration parameters
    `training` => `trainval` (?)

**Comment by drinkingkazu** [comment]
* `segmentation` to `result` or something
https://github.com/DeepLearnPhysics/lartpc_mlreco3d/blob/master/mlreco/trainval.py#L118

**Comment by Temigo** [comment]
Point 1 and 3 are included in pull request #16 . I think it is fine to keep `training` instead of `trainval` in the configuration parameters, because it is more intuitive (English).
