### ISSUE TITLE
Unify the network output format and input data

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#50]
`data_blob` and the network return (`forward` return) have different format currently, and `unwrap` functions I put in can a) unify the format and b) make one sensible format among options.
However, it's an option currently to be run only for `output_formatters`.

I'm thinking: shall we make this an option to run within the `trainval::forward` call? The upside is that we can expect a uniformly formatted data representations in anywhere downstream, and the downside is that it may spend some time shuffling data into the format (i.e. CPU time spent).
The reason why I ask is because we almost always want a unified, easy to interpret format, I think, and it's worth taking a small hit of processing time. (plus, currently downstream processing code like `output_formatters` and `analysis` written for two different formatting conventions = spreading a mess)

**Comment by bnels** [comment]
Is there a downside (other than CPU time)?

I'm in favor of having a consistent format if we can avoid breaking changes.

**Comment by drinkingkazu** [comment]
It will be a breaking change, but I think it's a change we want/need, and it will be a bigger breaking change as we wait (since the mess can only grow...)!

**Comment by drinkingkazu** [comment]
https://github.com/DeepLearnPhysics/lartpc_mlreco3d/commit/768e57128cfe7dd58b939b97f4f192319cb990e9
