### ISSUE TITLE
Rename `Chain` to `UResNetPPN` (in uresnet_ppn_chain.py)

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/lartpc_mlreco3d#65]
`Chain` is ambiguous name that should not be used anywhere (same applies for `cluster_chain_gnn.py`). Changing this probably causes a problem for loading network weights(?) w/o hacking the variable names upon loading. So I open an issue here to change at the right timing...

**Comment by Temigo** [comment]
Done.
