### ISSUE TITLE
PPN Output Parser

### ISSUE THREAD

**Issue by bnels** [DeepLearnPhysics/lartpc_mlreco3d#9]
There should be an easy way to turn PPN output into points.  This is currently not the case in `uresnet_ppn`.  I see two options:
1) Output points directly from forward function in PPN model
2) Have a parser function available that will give the output

The goal is to use this in a chain where we can feed the PPN positions into a GNN which will then use the positions for Primary identification

**Comment by Temigo** [comment]
I started implementing option 2. Sorry for not doing it earlier, I am still trying to figure out which algorithm is best to extract PPN predictions.

**Comment by bnels** [comment]
Here's a preliminary implementation of the parser:
https://github.com/bnels/lartpc_mlreco3d/blob/develop/mlreco/utils/ppn.py#L143
For context, here's how I use it in a chain with a GNN:
https://github.com/bnels/lartpc_mlreco3d/blob/develop/mlreco/models/chain_gnn.py#L42

**Comment by bnels** [comment]
Basically, the output of the function that selects candidate points should be a torch tensor with each row is
`[x,y,z,batch_id, label]` where `x,y,z,batch_id` are location and batch id, and `label` is the 5-types label.

**Comment by francois-drielsma** [comment]
This function exists (duplicated...) at lines:

https://github.com/DeepLearnPhysics/lartpc_mlreco3d/blob/eb006431565318aedcf9863b17f3e538e47dd8cb/mlreco/utils/ppn.py#L243

and 

https://github.com/DeepLearnPhysics/lartpc_mlreco3d/blob/eb006431565318aedcf9863b17f3e538e47dd8cb/mlreco/utils/ppn.py#L296

which seem to defer only in terms of default values. Should we get rid of one and close this?

**Comment by Temigo** [comment]
Sigh, this must be an artifact of git merge failure... I vote to get rid of one and close this issue.

**Comment by francois-drielsma** [comment]
You probably know which is the latest version better than I do! I'll let you choose which one to get rid of.

**Comment by Temigo** [comment]
Please use `uresnet_ppn_type_point_selector` in `mlreco.utils.ppn` and report bugs.
